config/routes.rb
Rails.application.routes.draw do

  authenticated :user, ->(user) { user.admin? } do
   get 'admin', to: 'admin#index'
   get 'admin/users'
   get 'admin/activity'
   get 'admin/dreams'
   get 'users/profile'
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/soñador/:id', to: 'users#profile', as: 'user'

  get 'dreams_in_process/olympic_games'
  get 'dreams_in_process/professional_athlete'
  get 'dreams_in_process/buy_dream'
  get 'dreams_in_process/become_independent'
  get 'dreams_in_process/good_leader'
  get 'dreams_in_process/find_passion'
  get 'dreams_in_process/new_skill'
  get 'dreams_in_process/find_dream_job'
  get 'dreams_in_process/find_love'
  get 'dreams_in_process/world_cup'
  get 'dreams_in_process/save_time_and_expenses'
  get 'dreams_in_process/attend_superbowl'
  get 'dreams_in_process/learn_personality'
  get 'dreams_in_process/aurora_borealis'
  get 'dreams_in_process/give_to_others'
  get 'dreams_in_process/better_person'
  get 'dreams_in_process/become_investor'
  get 'dreams_in_process/become_inventor'
  get 'dreams_in_process/another_planet'
  get 'dreams_in_process/fly'
  get 'dreams_in_process/young_and_retired'

  get 'registration/introduction'
  get 'registration/selection'
  get 'registration/quick_registration'
  get 'registration/part_1a'
  get 'registration/part_1b'
  get 'registration/part_2a'
  get 'registration/part_2b'

  get 'buy_dream/electronic', to: "buy_dream#electronic"

  get 'new_skill/coding'
  get 'new_skill/cook'
  get 'new_skill/new_language'
  get 'new_skill/design'
  get 'new_skill/robotics'
  get 'new_skill/freelancer'

  get 'profile/overview'
  get 'profile/sign_in'

  get 'save_time_and_expenses/save_the_time_in_the_market'
  get 'save_time_and_expenses/gasoline'
  get 'save_time_and_expenses/taking_care'
  get 'save_time_and_expenses/buy_from_productor'
  get 'save_time_and_expenses/laundry'
  get 'save_time_and_expenses/delivery_to_work'
  get 'save_time_and_expenses/pet_care'
  get 'save_time_and_expenses/clean_house'

  get 'friends/new_best_friends'
  get 'friends/bad_companies'

  get 'love/men'

  get 'health/espiritual'
  get 'health/fisical'
  get 'health/mental'
  get 'health/emocional'
  get 'health/pre_fisical'
  get 'health/fisical_better'
  get 'health/pre_mental'
  get 'health/mental_better'

  get 'happy/espiritual'
  get 'happy/family_united'
  get 'happy/give_to_others'
  get 'happy/life_purpose'

  get 'gamer/assemble_pc_gamer'
  get 'gamer/buy_pc_gamer'
  get 'gamer/buy_console'
  get 'gamer/buy_game'
  get 'gamer/travel_gamer'

  get 'house/buy_local_house'
  get 'house/build_local_house'
  get 'house/buy_house_abroad'
  get 'house/build_house_abroad'
  get 'house/house_exchange'
  get 'house/home_remodeling'
  get 'house/abroad_part_2'

  get 'new_car/car'
  get 'new_car/profit_car'
  get 'new_car/motorcycle'
  get 'new_car/vehicle_for_business'
  get 'new_car/bicycle'
  get 'new_car/luxury_car'

  get 'business/entrepeneur'
  get 'business/software'
  get 'business/no_initial_idea'
  get 'business/hardware'
  get 'business/local'
  get 'business/medical'
  get 'business/factory_production'
  get 'business/social_org'
  get 'business/food_and_beverages'
  get 'business/trading_company'
  get 'business/travel_and_tourism'

  get 'dreams/my_own_business'
  get 'dreams/travel'
  get 'dreams/gamer'
  get 'dreams/new_car'
  get 'dreams/new_house'
  get 'dreams/happy'
  get 'dreams/healthy'
  get 'dreams/friends'
  get 'dreams/new_skill'
  get 'dreams/buy_wish'
  get 'dreams/love'
  get 'dreams/save_time_and_expenses'

  get 'travel/europe'
  get 'travel/steps_travel'
  get 'travel/asia'
  get 'travel/america'
  get 'travel/africa'
  get 'travel/oceania'
  get 'travel/prueba'
  get 'travel/world/:dream_id', to: 'travel#world', as: :travel_world
  post 'travel/world/:dream_id', to: 'travel#create', as: :travel_create

  get 'pages/index'

  get 'add_dreams/add_new', to: "add_dreams#new"

  resources :add_dreams
  get 'add_dreams/new', to: "add_dreams#new"
  post 'add_dreams', to: "add_dreams#create"
  #get 'dreams', to: "dreams#dreams" 


root 'pages#index'
resources :dreams do
  resources :goals
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/add_dream.rb
class AddDream < ApplicationRecord
    belongs_to :user
    validates :plan_ideal, presence: true
    validates :descripcion, presence: true
    validates :sector_del_sueño, presence: true
    validates :nombre_del_sueño, presence: true
end

app/models/car_extra.rb
class Car_extra < ApplicationRecord
    belongs_to :goal
end

app/models/car_year.rb
class Car_year < ApplicationRecord
    belongs_to :goal
end

app/models/dream.rb
class Dream < ApplicationRecord
    has_many :goal
    belongs_to :user
end

app/models/gamer_extra.rb
class Gamer_extra < ApplicationRecord
    belongs_to :goal
end

app/models/goal.rb
class Goal < ApplicationRecord
    belongs_to :dream
end

app/models/house_extras.rb
class House_extras < ApplicationRecord
    belongs_to :goal
end

app/models/pc_gamer.rb
class Pc_gamer < ApplicationRecord
    belongs_to :goal
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :goal
end

app/models/travel.rb
class Travel < ApplicationRecord
    belongs_to :goal
end

app/models/travel_gamer.rb
class Travel_gamer < ApplicationRecord
    belongs_to :goal
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :dreams, dependent: :destroy  

  enum role: [:user, :admin, :moderator]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end

  include PublicActivity::Model
  tracked

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/helpers/gamer_helper.rb
module GamerHelper
end

app/helpers/happy_helper.rb
module HappyHelper
end

app/helpers/house_helper.rb
module HouseHelper
end

app/helpers/love_helper.rb
module LoveHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_link.html.erb
<%= link_to resource.name.capitalize, url_for([:admin, resource]), class:'btn btn-primary' %>

app/views/admin/_nav_links.html.erb
  <div class="panel-body">

   <p> <%= link_to "Admin", admin_path %><% "> #{params[:action]}.capitalize" unless params[:action].eql?("index") %> </p>

   <div class="btn-group">
    <%= render "admin/link", resource: User %>
    <%= link_to "Actividad", admin_activity_path %>
   </div>

  </div>      

app/views/admin/activity.html.erb
<div class="container">
 <h1 class= "text-center" >Administrador</h1>
 <%= render 'admin/nav_links' %>

<% @activities.each do |activity| %>
<li class= "list-group-item">
  <%= activity.id %>
  <%= activity.trackable_type %>
  <%= activity.trackable_id %>
  <%= link_to activity.trackable.name, activity.trackable %>
  <%= activity.key %>
  <%= activity.parameters %>
  <%= activity.created_at %>
  <%= activity.owner %>
</li>
<% end %>


</div>

app/views/admin/dreams.html.erb
<div class="container">
 <h1 class= "text-center" >Administrador</h1>
 <%= render 'admin/nav_links' %>

</div>

app/views/admin/index.html.erb
<div class="bg-main">
  <!--<div style="display: block; background-image: url(&quot;//d2c87l0yth4zbw-2.global.ssl.fastly.net/i/home/bg-albums.png&quot;);" class="bg-main-img lazy lazy-no-small" data-original="//d2c87l0yth4zbw-2.global.ssl.fastly.net/i/home/bg-albums.png"></div> -->
</div>

<div class="jumbotron jumbotron-albums jumbotron-subscriptions">
<div class="jumbotron-bg lazy lazy-no-small" style="background: url(../i/home/noise.png),linear-gradient(50deg,#010609 0,#1967bf 100%);" data-original=""></div>
  <div class="container">
   <div class="col-sm-12">
          <div class="row">
            <div class="col-sm-10 col-lg-12">
              <div style="margin-top: 40px;" class="animated animatedFadeInUp">
                <h2>
                  <span class="text-white">
                     <%= current_user.username %> Administrador 
                  </span>
                </h2>
              </div>
              <div class="animated animatedFadeInUp">
                <p class="text-white">
            Noblidream es nuestra aportación para ayudar a la humanidad a que llegue a ser algo de lo que todos estemos orgullosos de ser parte, con la esperanza de seguir moviendo a todos hacia nuestro mejor futuro. Podras cumplir cualquier cosa que hayas pensado alguna vez e incluso mejoraras tus actividades diarias.
            Gracias por confiar en nosotros y a continuacion te presentamos nuestra vision. 
                </p>
              </div>
            </div>
          </div>
          </div>
      </div>
      </div>
  <div class="jumbotron">
    <div class="container altura bg-white">
      <div class="row">
        <div style="max-width: 100%; margin: 20px auto; border: 1px solid #ddd; box-shadow: 2px 2px 0px 1px rgba(0,0,0,0.07); 
        background: #fff; border-radius: 4px;">
        <div>
          <p>Aqui puedes cambiar tus datos personales, introduce los datos que quieras actualizar y deja en blanco los campos que no deseas actualizar</b></p>
        </div>
        <div class="ui-153">

  <div class="panel-body">

    <%= render 'admin/nav_links' %>

  </div>      
        </div>
</div>
      </div>
</div>
</div>

app/views/admin/users.html.erb
<div class="container">
 <h1 class= "text-center" >Administrador</h1>
 <%= render 'admin/nav_links' %>

 <table class="table table-dark table-striped">
    <thead>
        <tr>
        <th scope="col">User_id</th>
        <th scope="col">Email</th>
        <th scope="col">Name</th>
        <th scope="col">Username</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        <tr>
         <th> <%= user.user_id %> </th>
         <td> <%= link_to user.title.truncate(15), admin_user_path(user) %> </td>
         <td> <%= user.name %> </td>
        </tr>
        <% end %> 
    </tbody>
 </table>

</div>